### PR TITLE
feat: added util functions 

### PR DESCRIPTION
**Pull request by impelcrypto**
* feat: added util functions 
  * these functions will be exported to Astar portal

### CODE REVIEW

**Comment by impelcrypto** [comment]
Hi @niklabh 
I got this error when I run `yarn build` (and the warnings will appear on the frontend app). Could you take a look? 🙏 

image

**Comment by impelcrypto** [comment]
Hi @niklabh 
It seems like functions exported from astar-js won't come with type annotation. Could you help take a look?

= examples =
For this, `capitalize` should returns `string`

Astar-js
image

Astar Portal
image

For this, I'd like to avoid adding `typeof` in front of the type/interface imported from `astar-js`

Astar Portal
image

**Comment by impelcrypto** [comment]
Hi @niklabh 
I've resolved type annotation issue (in [this ](https://github.com/AstarNetwork/astar.js/pull/30/commits/bdb9258ed9ec53cae824e054212e735ef18e0cdd#diff-0b280a445be167f54cd916c0718c952b8e0d4ca9621903d05eec25efd4c6ed6dR7)line).

**Comment by impelcrypto** [comment]
@niklabh 
Please keep check [this](https://github.com/AstarNetwork/astar.js/pull/30#issuecomment-1375432761) issue.

**Comment by impelcrypto** [comment]
@niklabh 
Not sure if [this](https://github.com/AstarNetwork/astar.js/pull/30/commits/165d080f9812a4c3bccdff5ad3df0f37b035da12) commit makes sense to you but it looks like [the version issue](https://github.com/AstarNetwork/astar.js/pull/30#issuecomment-1375432761) has been resolved.

1. It looks like `build`, `test` and `lint` are failed, could you take a look? I think there still have a version issue (you can check with `yarn test`)  
2. Do you know why `yarn upgrade --pattern @polkadot --latest` doesn't work in this repo?

image

**Comment by impelcrypto** [comment]
@niklabh 

1. I've update `pr-any.yml` [in this](https://github.com/AstarNetwork/astar.js/pull/30/commits/2c71306f064c34a4e86a607fda9a00994f62d9a1) commit, please take a look. Still getting an error in `build` checks in CI.
2.  After updated Polkadot.js packages, some code doesn't work properly. You may want to check these files.

https://github.com/AstarNetwork/astar.js/actions/runs/3926818642/jobs/6712929764

https://github.com/AstarNetwork/astar.js/pull/30/commits/685d935a1b4fa3a1ec045920a63f63ef0620622e

**Review by niklabh — APPROVED** [review]

**Review by sirius651 — APPROVED** [review]

**Pull request merged**
